<!DOCTYPE html>
<html>
<head>
	<meta charset"utf-8" />
	<title>Encoding Status</title>
	<link href="css/lava.css" rel="stylesheet" type="text/css" />
</head>
<body class="lava">
<div class="wrapper">	
	<div class="container">
		<h1>Hi!</h1>

	</div>
</div>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
<script src="js/application.js" type="text/javascript"></script>

</body>
</html>